cs179_django_files/cs179_yelp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #creates a path time using the function from views
    path('', views.home, name='home'),
    #anytime you see the app: service, include the urls.py
        #using name for namespace when it has sub files 
    path('service/',include('service.urls', namespace='service'))
]

cs179_django_files/service/urls.py
from django.urls import path
from . import views

app_name ="service"

urlpatterns = [
    #creates a path time using the function from views
    #need to include this in the root directory in package level directory
    path('list/', views.service_list, name="list"),
]

cs179_django_files/service/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    birthdate = models.DateField()
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
    	return self.name + " " + self.email 

class Users(models.Model): 
	userID = models.CharField(max_length = 30)
	username = models.CharField(max_length = 250)

	#override 
	#class Meta: 
	def __str__(self):
		return self.username

class Business(models.Model): 
	bid = models.CharField(max_length = 100) 
	name = models.CharField(max_length = 50) 
	avgstars = models.CharField(max_length = 3)
	categories = models.CharField(max_length = 200)

class Reviews(models.Model): 
	bid = models.ForeignKey(Business, on_delete=models.CASCADE) 
	text = models.CharField(max_length = 100) 
	stars = models.CharField(max_length = 3)
	prediction = models.CharField(max_length = 3, default='0') 
	userID = models.ForeignKey(Users, on_delete=models.CASCADE)
	rid = models.CharField(max_length = 30) 


	#def prediction():
	#	return aggregate(Avg(prediction)) 

	#def __str__(self):
	#	return self.text
	

cs179_django_files/cs179_yelp/views.py
from django.shortcuts import render 

def home(request):
	#creates key value pairs
	context = {}
	return render(request, 'home.html', context)

cs179_django_files/service/views.py
from django.shortcuts import get_object_or_404, render, HttpResponse
from tablib import Dataset 
from .models import Business, Reviews, Users
from itertools import chain 
from django.db.models import Avg

#render(request, template file, context)

def service_list(request):
	"""
	Renders the service_list template that list all the currently available polls 
	"""
	business = Business.objects.all()
	review = Reviews.objects.all() 
	user = Users.objects.all() 

	business_list = ''
	review_list = '' 
	review_list1 = ''
	business_results = ''
	user_list = '' 
	
	#grabbing data from the search bar 
	if 'search' in request.GET:
		search_term = request.GET['search']
		business_list = business.filter(name__icontains=search_term)
		review_list = review.filter(bid__in=business_list)
		user_list = user.filter(userID__in=review_list) 


		#prediction_total = review_list.aggregate(Avg('prediction')) 

	context = {'business': business, 'business_list': business_list, 'review_list': review_list }
	return render(request, 'service/service_list.html', context)


def simple_upload(request):
	if request.method == 'POST':
		person_resource = PersonResource()
		dataset = Dataset()
		new_persons = request.FILES['myfile']

		imported_data = dataset.load(new_persons.read())
		result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

	if not result.has_errors():
		person_resource.import_data(dataset, dry_run=False)  # Actually import now

	return render(request, 'service/import.html')

cs179_django_files/service/templates/service/business_detail.html
{% extends 'base.html' %}

{%block content%}
<h1> Business detail page </h1>
{{ business }}



{% endblock  %}

cs179_django_files/service/templates/service/import.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

cs179_django_files/service/templates/service/service_list.html
{% extends 'base.html' %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

{% block content %}
<div class ="container">

	<h1><center> Enter your business name below </h1></center>
	<u1>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <div class="container">
    <br/>
    <div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm">
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>
                                    <!--end of col-->
                                    <div class="col">
                                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="Search" name ='search' value = "{{search_term}}">
                                    </div>
                                    <!--end of col-->
                                    <div class="col-auto">
                                        <button class="btn btn-lg btn-success" type="submit">Search</button>
                                    </div>
                                    <!--end of col-->
                                </div>
                            </form>
                        </div>
                        <!--end of col-->
                    </div>
</div>
  <!-- NEED THIS TO SEARCH FOR RESULTS, shows business --> 

  {% for i in business_list %} 
    <h2> Name of Business: {{ i.name }}</h2>
    <h2> Business ID: {{i.bid}}</h2>
    <h2> Average star ratings: {{i.avgstars}} </h2>  
  {% endfor %}

  {%for i in records%} 
      <h2> {{i}} </h2>
  {% endfor %}

  <h2> Customer Reviews:</h2> 
  {% for i in review_list %}
     <h2> Prediction: {{i.prediction}} Review: {{ i.text }}  Customer: {{i.userID }} </h2> 
  {% endfor %}



  <!---{%for i in review_and_user%}
    <h2> Outputting with conjoined list: {{ i.review }} {{i.username}}</h2> 
  {% endfor %} --> 
  
	</u1>
</div>
{% endblock %}

cs179_django_files/templates/base.html
<!DOCTYPE html>
{% load static %} 

<head> 
	<title>CS179G Senior Design Project</title>

	<!--NEED FOR THIS BOOTSTRAP--> 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	{% block custom_css%}{% endblock %}
</head> 

<body> 
	{% include 'includes/navbar.html' %}
	{% block content %}
	  <!--this will be overwritten that defines base.html --> 
	{% endblock %}

<!--NEED THESE FOR BOOTSTRAP --> 
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X										+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="							sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<!--JAVASCRIPT FOR BOOTSTRAP -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

cs179_django_files/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
<link rel='stylesheet' type = 'text/css' href = "{% static 'css/home_styles.css' %}">
{% endblock %}

{% block content %}

<div class ="container"> 
	<div class = "row"> 
		<div class ="col">
			<div id="home-content"> 
				<h1>Welcome to our Senior Design Project </h1>
				<h3> Team members: Andrea-Cruz Castillo, Tiffany Cedeno, Patrick Ngyuen </h3>
				<h2> Click Service to start </h2>

				<hr> 
			</div>
		</div> 
	</div>

</div>
{% endblock %}

cs179_django_files/templates/import.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

cs179_django_files/templates/includes/navbar.html
<!--navigation bar located in front page --> 
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNav">
    		<ul class="navbar-nav">
      			<li class="nav-item active">
        			<a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
      			</li>
      			<li class="nav-item">
        			<a class="nav-link" href="{% url 'service:list' %}">Service</a>
      			</li>
      		
    		</ul>
  		</div>
	</nav>